### ISSUE TITLE
Test status info on Ultimaker2's

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/WiFi-Box#11]
With https://github.com/Doodle3D/doodle3d-firmware/pull/65 Ultimaker2's (2go, extended etc, plus etc) should show status info 'Doodle3D heat up...', 'Doodle3D printing...' and 'Doodle3D done! on the display'. 
- [x] With Ultimaker 2 try making two prints (without rebooting printer or WiFi-Box):
  - [x] It shows the above mentioned statuses? 
  - [x] This doesn't break anything (like the regular menu's)?
- [ ] With Ultimaker 2 go try making one print
  - [ ] It shows the above mentioned statuses? 
  - [ ] This doesn't break anything (like the regular menu's)?
- [ ] With Ultimaker 2 go try making one print but stopping the print. Does it display 'Doodle3D done!'?

**Comment by jeroensomers** [comment]
> With Ultimaker 2 try making two prints (without rebooting printer or WiFi-Box):

Done

> It shows the above mentioned statuses?

Yes on the UM2 it shows al three statuses.

> This doesn't break anything (like the regular menu's)?

No everything works fine

> With Ultimaker 2 go try making one print

Done

> It shows the above mentioned statuses?

No it shows "Printing with USB..." (firmware version 15.04)

I updated the firmware with Cura 2.1.0 This gave the firmware version 2.1
It still shows "Printing with USB..."

I updated the firmware with Cura 15.04.3 This gave the firmware version 15.04.3
it still shows "Printing with USB..."

> This doesn't break anything (like the regular menu's)?

No everything works fine

> With Ultimaker 2 go try making one print but stopping the print. Does it display 'Doodle3D done!'? 

No it doesn't say 'Doodle3D done!" it says "Printing with USB..."

**Comment by peteruithoven** [comment]
With the beta version, in the settings window, could you try pressing the Restore settings to defaults button? This should retrieve the latest defaults and enable this feature. Could you then try the 2go test again? More info: https://github.com/Doodle3D/doodle3d-firmware/pull/65#issuecomment-226145239

**Comment by jeroensomers** [comment]
YES,

When I pressed the "Restore settings to defaults" button, all settings where restored and the display says all three sentences (heating.. printing... done...)

The start and end gcode where not refreshed within the box, but now they are.

**Comment by peteruithoven** [comment]
Awesome
