### ISSUE TITLE
Test feature/button switch wificonfig

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/WiFi-Box#12]
With https://github.com/Doodle3D/doodle3d-firmware/pull/62 it should become an access point when pressing the reset button for 4 or more seconds. 
- [x] It becomed properly names access point?
- [x] Wifi related config is correctly changed after pressing reset button? 
- [x] Failsave still works? 
- [x] Can we still call d3dapi from commandline? 
- [x] After reboot it starts the new access point? 
- [x] After pressing button we can connect to it properly?
- [x] After reboot we can connect to it properly?
- [x] /d3dapi/network/reset also creates access point?

**Comment by peteruithoven** [comment]
> It becomed properly names access point?

Yes; Doodle3D-4CC28C 

> Wifi related config is correctly changed after pressing reset button? 

`/etc/config/wireless` went from:

```
config wifi-device 'radio0'
    option type 'mac80211'
    option hwmode '11g'
    option path 'platform/ar933x_wmac'
    option htmode 'HT20'
    option disabled '0'

config wifi-iface
    option disabled '0'
    option network 'wlan'
    option encryption 'psk2'
    option device 'radio0'
    option mode 'sta'
    option key '...'
    option ssid 'Vechtclub XL F1.19'

config wifi-iface
    option network 'wlan'
    option encryption 'none'
    option device 'radio0'
    option mode 'ap'
    option ssid 'Doodle3D-4CC28C'
    option disabled '1'

config wifi-iface
    option device 'radio0'
    option network 'lan'
    option mode 'ap'
    option ssid 'OpenWrt'
    option encryption 'none'
    option disabled '1'
```

To:

```
config wifi-device 'radio0'
    option type 'mac80211'
    option hwmode '11g'
    option path 'platform/ar933x_wmac'
    option htmode 'HT20'
    option disabled '0'

config wifi-iface
    option network 'wlan'
    option encryption 'none'
    option device 'radio0'
    option mode 'ap'
    option ssid 'Doodle3D-4CC28C'
    option disabled '0'
```

Which seems okay. 

> Failsave still works? 

Yes

> Can we still call d3dapi from commandline? 

Yes

> After reboot it starts the new access point?

Yes; Doodle3D-4CC28C

**Comment by olijf** [comment]
@peteruithoven maybe we also need to test the new API entry?

**Comment by peteruithoven** [comment]
Good point

**Comment by peteruithoven** [comment]
> After pressing button we can connect to it properly?

Yes

> After reboot we can connect to it properly?

Yes

> /d3dapi/network/reset also creates access point? 

Using the Chrome app Postman I tried this and it created the access point.

**Comment by olijf** [comment]
ah ok, but nothing is displayed?

**Comment by peteruithoven** [comment]
I didn't get a response, but then again I didn't test this using the ethernet cable, so that makes sense right?
