### ISSUE TITLE
Test feature/always available

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/WiFi-Box#13]
With https://github.com/Doodle3D/doodle3d-firmware/pull/63/files it should become an accesspoint when it can't connect to a WiFi network (when using the api). 

Update to the latest beta (0.10.11-...)
- [x] Does it still connect to WiFi networks? 
- [x] When the wrong password is given it becomes an access point? Does it have the proper name (e.g. Doodle3D-4CC28C)
  - [x] Try this on desktop computer using connect.doodle3d.com. Does it give some useful feedback?
  - [x] When you then give the right password it does connect properly? 
  - [x] Try this on desktop computer using the settings popup. Does it give some useful feedback? 
  - [x] When you then give the right password it does connect properly? 
  - [x] Try this on a tablet / mobile phone. The tablet / phone will probably switch back to a previous wifi and not give feedback? 
  - [x] When you connect to created access point and try this again with the right password it does connect properly?
- [x] When the wrong ssid is given it becomes an acccess point? How: Create hotspot with mobile, select as target network, disable hotspot, attempt to connect to network. 
  - [x] Try this on desktop computer using connect.doodle3d.com. Does it give some useful feedback?
  - [x] When you then enable the hotspot again, can it connect properly? 
- [x] When a wrong password is given and it became a access point and then the WiFi-Box is rebooted, does it become that access point again? 

In comment, mention specific WiFi-Box version. Tick / check all successfully completed test above. Quote all completed tests and share result behind each test. for example: 

> Does it still connect to WiFi networks? 

Yes, without any problems. 

> When the wrong password is given it becomes an access point? 
>   Try this on desktop computer using connect.doodle3d.com. Does it give some useful feedback?

It became an access point (Doodle3D-4CC28C) and it indicated: "Failed connecting to WiFi-network".

**Comment by jeroensomers** [comment]
> Does it still connect to WiFi networks? 

Yes, without any problems

**Comment by jeroensomers** [comment]
> When the wrong password is given it becomes an access point? Does it have the proper name (e.g. Doodle3D-4CC28C) 
> Try this on desktop computer using connect.doodle3d.com. Does it give some useful feedback?

It became an access point (Doodle3D-75BFD0) but I got no indication: "Failed connecting to WiFi-network".

**Comment by jeroensomers** [comment]
> When you then give the right password it does connect properly?

Yes, without any problems. (by both connection options)

**Comment by jeroensomers** [comment]
> Try this on a tablet / mobile phone. The tablet / phone will probably switch back to a previous wifi and not give feedback? 

It didn't switch back when I gave the wrong password, the site gave me the following message: `Something went wrong, please try again`

**Comment by jeroensomers** [comment]
>  When you connect to created access point and try this again with the right password it does connect properly?

Yes, without any problems

**Comment by jeroensomers** [comment]
> When the wrong ssid is given it becomes an acccess point? How: Create hotspot with mobile, select as target network, disable hotspot, attempt to connect to network.
> 
> Try this on desktop computer using connect.doodle3d.com. Does it give some useful feedback?

It works but it does not give any feedback.

> When you then enable the hotspot again, can it connect properly?

Yes, it connects properly

**Comment by jeroensomers** [comment]
> When a wrong password is given and it became a access point and then the WiFi-Box is rebooted, does it become that access point again? 

Yes, it becomes a accesspoint again.

**Comment by peteruithoven** [comment]
> > Try this on a tablet / mobile phone. The tablet / phone will probably switch back to a previous wifi and not give feedback? 
> 
> It didn't switch back when I gave the wrong password, the site gave me the following message: `Something went wrong, please try again`

This is great, I expected the device to switch. We should try this a couple of times, just because it's good to know how it behaves. But for now it's tested and the changes seem release ready.
